spring:
  profiles:
    active:
      - local

    group:
      local:
        - localdb
        - secret
        - smtp
        - springdoc
        - naverapi

      production:
        - production
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true

init:
  excel:
    path: excel/baseinfo.xlsx


lms:
  login-url: https://lms.jdnc.or.kr/auth/login_check
  my-info-url: https://lms.jdnc.or.kr/mypage/myInfo

cloud:
  aws:
    s3:
      bucket: jdnclib-s3
    stack.auto: false
    region.static: ap-northeast-2


management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: /health-check

  endpoint:
    health:
      show-details: always