spring:
  profiles:
    active:
      - local

    group:
      local:
        - localdb
        - secret

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

lms:
  login-url: https://lms.jdnc.or.kr/auth/login_check
  my-info-url: https://lms.jdnc.or.kr/mypage/myInfo