spring:
  profiles:
    active:
      - production

    group:
      local:
        - localdb
        - secret
        - smtp
        - springdoc

      production:
        - production
        - secret
        - smtp

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

lms:
  login-url: https://lms.jdnc.or.kr/auth/login_check
  my-info-url: https://lms.jdnc.or.kr/mypage/myInfo