spring:
  profiles:
    active:
      - production

    group:
      local:
        - localdb
        - secret
        - smtp
        - springdoc
        - naverapi

      production:
        - production
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

lms:
  login-url: https://lms.jdnc.or.kr/auth/login_check
  my-info-url: https://lms.jdnc.or.kr/mypage/myInfo

init:
  admin:
    username: admin
    password: test1234

cloud:
  aws:
    s3:
      bucket: jdnclib-s3
    stack.auto: false
    region.static: ap-northeast-2


management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: /health-check

  endpoint:
    health:
      show-details: always